# CRC-16 Configuration
polynomial: 0x1021  # Standard CRC-16-CCITT polynomial
initial_value: 0xFFFF  # Initial value
final_xor: 0x0000  # Final XOR value
reflect_input: true  # Reflect input bytes
reflect_output: true  # Reflect output CRC
data_processing: "Raw Data"  # Process raw data including DLE and SOH bytes