# CRC-16 Configuration
crc:
  # Parameters for DEX_CUSTOM with XOR that matched in the analysis
  algorithm: "DEX_CUSTOM"  # Use the DEX custom algorithm
  init: 0x0000  # Initial value from match
  xor_out: 0x0d4d  # Final XOR value from match
  # Metadata for reference
  data_processing: "Raw Data"  # How data is processed
  crc_location: "CRC at End"  # Where CRC is located
  endianness: "LE"  # Little-endian format